name: Deploy preview

on:
  pull_request:
  schedule:
    - cron: 23 4 * * 1/2

jobs:
  deploy-branch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: branchname

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          production_environment: false
          environment: 'vercel/${{ steps.branchname.outputs.branch }}'

      - uses: actions/checkout@v2
      - name: Deploy to Vercel
        id: deploy-to-vercel
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alias-domains: '{{BRANCH}}-wundf-web.errnesto.vercel.app'
  
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: '${{ github.token }}'
          state: 'success'
          environment_url: ${{ steps.deploy-to-vercel.outputs.preview-url }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: '${{ github.token }}'
          state: 'failure'
          environment_url: ${{ steps.deploy-to-vercel.outputs.preview-url }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
