name: Deploy preview

on:
  pull_request:
  schedule:
    - cron: 4 14 * * *

jobs:
  deploy-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Vercel
        id: deploy-to-vercel
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alias-domains: '{{BRANCH}}-wundf-web.errnesto.vercel.app'
    outputs:
      preview-url: ${{ steps.deploy-to-vercel.outputs.preview-url }}
